# Generated by Django 5.1.4 on 2024-12-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_user_avatar'),
        ('user_management', '0003_user_is_2fa_enabled'),
    ]

    operations = [
    ]
