name: "코드 수정"
description: 코드 수정 Issue 작성 양식입니다.
labels: ["refactoring"]
body:
  - type: markdown
    attributes:
      value: |
        작성 예시 : "[REFACTORING] 경로 계산 로직 최적화"
  - type: textarea
    id: refactoring-description
    attributes:
      label: 작업 설명
      description: 어떤 코드를 수정하시는 건지 적어주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 수정 이유 (선택 사항)
      description: 수정하는 이유에 대해서 설명해주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: false
