# Generated by Django 5.1.3 on 2024-12-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='chatroom_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
